# Generated by Django 5.0.3 on 2024-04-03 11:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_auth_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='user-photos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'png', 'svg', 'heic', 'heif', 'webp'])]),
        ),
    ]
