# Generated by Django 5.0.3 on 2024-04-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_rename_postcomment_comment_alter_post_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(upload_to='post-users/% Y/% m/% d/'),
        ),
    ]
