# Generated by Django 5.0.3 on 2024-04-13 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_post_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.ImageField(upload_to='post-users/'),
        ),
    ]
